EShop/Models/Category.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EShop.Models
{
    public class Category
    {
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }

        public ICollection<Product> Product { get; set; }
    }
}

EShop/Models/ErrorViewModel.cs
namespace EShop.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EShop/Models/Order.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EShop.Models
{
    public class Order
    {
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        [StringLength(250)]
        public string ProductName { get; set; }
        public int Quantity { get; set; }
        [Column(TypeName = "decimal(18,4)")]

        public decimal OldPrice { get; set; }
        [Column(TypeName = "decimal(18,4)")]

        public decimal ActualPrice { get; set; }
        public int Discount { get; set; }
        public int ProductId { get; set; }
        public Product Product { get; set; }

    }
}

EShop/Models/Product.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EShop.Models
{
    public class Product
    {
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        [StringLength(250)]
        public string Name { get; set; }
        [Required]
        [StringLength(500)]
        public string Description { get; set; }

        [Column(TypeName = "decimal(18,4)")]
        public decimal Price { get; set; }
        public int Discount { get; set; }
        [Required(ErrorMessage = "Select category")]
        public int CategoryId { get; set; }
        public Category Category { get; set; }
        [NotMapped]
        public IEnumerable<SelectListItem> Categories = null;
        [NotMapped]
        public int Quantity = 1;

    }
}

EShop/Models/ProductViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections;
using System.Collections.Generic;

namespace EShop.Models
{
    public class ProductViewModel
    {
        public IEnumerable<SelectListItem> Categories { get; set; }
        public IEnumerable<Product> Products { get; set; }
        public int CategoryId { get; set; }
        public int CurrentPage { get; set; }
        public int productCount { get; set; }
    }
}

EShop/Controllers/AdminController.cs
using EShop.Data;
using EShop.Models;
using EShop.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace EShop.Controllers
{
    public class AdminController : Controller
    {

        private readonly IProduct _product;
        private readonly ICategory _category;
        private readonly IUnitOfWork _unitOfWork;

        public AdminController(IProduct product , ICategory category,IUnitOfWork unitOfWork)
        {
            _product = product;
            _category = category;
            _unitOfWork = unitOfWork;
        }
        public IActionResult Product(int categoryId=0)
        {
            var categories = _category.GetCategories().Select(c=>
                 new SelectListItem
                 {
                     Text = c.Name,
                     Value = c.Id.ToString()
                 }
            );
            var products = _product.GetProducts(categoryId).ToList();
            var productViewModel = new ProductViewModel { Products = products, Categories = categories , CategoryId = categoryId };
            return View(productViewModel);
        }
        public IActionResult Edit(int id)
        {
            var product = _product.GetProductById(id);
            if (product == null) return RedirectToAction(nameof(Product));
            product.Categories = _category.GetCategories().Select(c=>
                new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                }
            );

            return View(product);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Product product)
        {

            var oldProduct = _product.GetProductById(product.Id);
            if (product == null) return RedirectToAction(nameof(Product));
            oldProduct.Price = product.Price;
            oldProduct.Name = product.Name;
            oldProduct.CategoryId = product.CategoryId;
            oldProduct.Discount  = product.Discount;
           _unitOfWork.SaveChanges();

            return RedirectToAction(nameof(Product));
        }
        
        public IActionResult Create()
        {
            var product = new Product();
            var categories = _category.GetCategories().Select(c=>
                new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                }
            );
            product.Categories = categories;
            return View(product);
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Create(Product product)
        {
            _product.Create(product);
            _unitOfWork.SaveChanges();

            return RedirectToAction(nameof(Product));
        }
    }
}

EShop/Controllers/HomeController.cs
using EShop.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace EShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EShop/Controllers/OrderController.cs
using EShop.Models;
using EShop.Repository;
using Microsoft.AspNetCore.Mvc;

namespace EShop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IProduct _product;

        public OrderController(IProduct product)
        {
            _product = product;
        }
        public IActionResult PlaceOrder(int id, int qty =1)
        {
            var product = _product.GetProductById(id);
            if (product == null) return NotFound();
            var order = new Order
            {
                Quantity = qty,
                ProductId = product.Id,
                Discount = product.Discount,
                OldPrice = product.Price,
                ProductName = product.Name, 
            };
            if (product.Discount > 0 && qty > 1)
            {
                order.ActualPrice = (qty *(product.Price)) - ((product.Price) * 10 / 100);
            }
            else
            {
                order.ActualPrice = product.Price;
            }
            return View(order);
        }
    }
}

EShop/Controllers/ProductsController.cs
using EShop.Data;
using EShop.Models;
using EShop.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace EShop.Controllers
{
    public class ProductsController : Controller
    {

        private readonly IProduct _product;

        public ProductsController(IProduct product)
        {
            _product = product;
        }
        public IActionResult Index(int page=0)
        {
            var products = _product.GetProducts();
            var count =Convert.ToDecimal(products.Count());
            decimal dividr = count / 5;
            var ceilling = Convert.ToInt16(Math.Ceiling(dividr));

            if (page == 0)
                page = 1;
            products = products.Skip((page - 1) * 5).Take(5);

            var viewModel = new ProductViewModel { Products = products.ToList() , productCount = ceilling , CurrentPage = page};
            return View(viewModel);
        }
       
    }
}

EShop/Views/Admin/Create.cshtml
@model Product
<div class="container">
    <form method="post" asp-action="Create">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="form-group">
            <label for="name">Name</label>
            <input asp-for="Name" type="text" class="form-control" id="name">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <br />
        <div class="form-group">
            <label for="desc">Description</label>
            <input asp-for="Description" type="text" class="form-control" id="desc" >
            <span asp-validation-for="Description" class="text-danger"></span>

        </div>
        <div class="form-group">
            <label for="price">Price</label>
            <input asp-for="Price" type="text" class="form-control" id="price">
            <span asp-validation-for="Price" class="text-danger"></span>

        </div>
        <div class="form-group">
            <label for="discount">Discount % </label>
            <input asp-for="Discount" type="number" class="form-control" id="discount" value="0" >
            <span asp-validation-for="Discount" class="text-danger"></span>

        </div>
        <div class="form-group">
            <label for="category">Category</label>
            <select asp-for="CategoryId" class="form-control" asp-items="@Model.Categories">
                <option disabled selected>--Select Category--</option>
            </select>
            <span asp-validation-for="CategoryId" class="text-danger"></span>

        </div>

        <button type="submit" class="btn btn-success">Create</button>
    </form>
</div>
@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

EShop/Views/Admin/Edit.cshtml
@model Product
<div class="container">
    <form method="post" asp-action="Edit">
        <input hidden asp-for="@Model.Id"/>
      <div class="form-group">
        <label for="name">Name</label>
        <input asp-for="@Model.Name" type="text" class="form-control" id="name" value="@Model.Name" >
      </div>
      <br />
      <div class="form-group">
        <label for="desc">Description</label>
        <input asp-for="@Model.Description" type="text" class="form-control" id="desc" value="@Model.Description">
      </div>
      <div class="form-group">
        <label for="price">Price</label>
        <input asp-for="@Model.Price" type="text" class="form-control" id="price" value="@Model.Price.ToString("##")">
      </div>
        <div class="form-group">
            <label for="discount">Discount % </label>
            <input asp-for="@Model.Discount" type="number" class="form-control" id="discount" value="@Model.Discount">
        </div>
      <div class="form-group">
        <label for="category">Category</label>
        <select asp-for="CategoryId" class="form-control" asp-items="@Model.Categories">
            <option disabled selected>--Select Category--</option>
        </select> 
      </div>

      <button type="submit" class="btn btn-primary">Edit</button>
</form>
</div>

EShop/Views/Admin/Product.cshtml
@model ProductViewModel

<div class="container mt-5 mb-3">
    
    <div class="row">
        <div class="col-md-5 mb-2">
            <a class="btn btn-primary" asp-action="Create">Add Product</a>
        </div>
      
        <div class="col-md-9 mb-3">
            <select class="form-control" id="categoryfilter" >
                <option disabled selected>--Select Category--</option>
                @foreach (var category in Model.Categories)
                {
                    if(category.Value == Model.CategoryId.ToString()){
                        <option selected value="@Url.Action("Product","Admin",new{ categoryId=category.Value })">@category.Text</option>
                    }else{
                        <option value="@Url.Action("Product","Admin",new{ categoryId=category.Value })">@category.Text</option>

                    }
                }
            </select>
        </div>
       
        <br />
        @if (Model.Products.Count() >0)
        {
            @foreach (var product in Model.Products)
            {
                 <div class="col-md-4">
                    <div class="card p-3 mb-2">
                        <div class="d-flex justify-content-between">
                            <div class="d-flex flex-row align-items-center">
                                <div class="icon"> <i class="bx bxl-mailchimp"></i> </div>
                                <div class="ms-2 c-details">
                                    <h6 class="mb-0">@product.Name</h6>
                                </div>
                            </div>
                           
                        </div>
                        <div class="mt-5">
                            <h3 class="heading">@product.Name<br>@product.Description</h3>
                            <div class="row">
                                <div class="mt-3"> <strong class="text1">@product.Price.ToString("##")<span class="text2">LE</span></strong> </div>
                                <div class="mt-2">
                                    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@product.Id">Edit</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
          
        }else
        {
            <p>No product to view</p>
        }
    </div>
    
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#categoryfilter").on("change",function(){
            window.location = $(this).find(":selected").val();
        });
    });
</script>

EShop/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EShop/Views/Order/PlaceOrder.cshtml
@model Order
<div class="container">
    <form method="post" asp-action="">
        <div class="form-group ">
            <label for="name">Name</label>
            <input asp-for="ProductName" type="text" disabled class="form-control" id="name">
        </div>
        <br />
        <div class="form-group  mb-1">
            <label for="desc">Quantity</label>
            <input asp-for="Quantity" disabled type="text" class="form-control" id="Qty">

        </div>
        <div class="form-group  mb-1">
            <label for="discount">Discount % </label>
            <input asp-for="Discount" disabled type="number" class="form-control" id="discount" value="0">
 
        </div>
        <div class="form-group mb-1">
            <label for="price">Price</label> 
            <input asp-for="ActualPrice" type="text" disabled class="form-control" id="price"> 
        </div>

        <button type="submit" class="btn btn-success">Place Order</button>
    </form>
</div>

EShop/Views/Products/Index.cshtml
@model ProductViewModel


    <div class="container mt-5 mb-3">
    <div class="row">
       @if (Model.Products.Count() >0)
        {
            @foreach (var product in Model.Products)
            {
                <div class="col-md-4">
                        <div class="card p-3 mb-2">
                            <div class="d-flex justify-content-between">
                                <div class="d-flex flex-row align-items-center">
                                    <div class="icon"> <i class="bx bxl-mailchimp"></i> </div>
                                    <div class="ms-2 c-details">
                                        <h6 class="mb-0">@product.Name</h6>
                                    </div>
                                </div>

                            </div>
                            <div class="mt-5">
                                <h3 class="heading">@product.Name<br>@product.Description</h3>
                                <div class="row">
                                    <div class="mt-3">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <strong class="price">
                                                    @product.Price.ToString("##")
                                                    <span class="text2">LE</span>
                                                </strong>
                                            </div>
                                            <div class="col-md-4">
                                                <div class='quantity'>
                                                    <input type='button' value='-' class='qtyminus minus' field='quantity' />
                                                    <input asp-for="@product.Quantity" type='text'  class='qty' />
                                                    <input type='button' value='+' class='qtyplus plus' field='quantity' />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="mt-2">
                                    <button class="btn btn-primary submit" data-url="@Url.Action("PlaceOrder","Order")" data-id="@product.Id" id="submit">buy now</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                </div>
                
            }
            <div class="row" style="width:40%;margin-left:30%">
                <table cellpadding="0" cellspacing="0" >
                    <tr>
                        @for (int i = 1; i <= Model.productCount; i++)
                        {
                            <td>
                                @if (i != Model.CurrentPage)
                                {
                                    <a asp-action="Index" asp-controller="Products" asp-route-page="@i">@i</a>
                                }
                                else
                                {
                                    <span>@i</span>
                                }
                            </td>
                        }
                    </tr>
                </table>
            </div>
          
          
        }else
        {
            <p>No product to view</p>
        }
        </div>
    </div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>
        $(document).ready(($) => {
            $('.quantity').on('click', '.plus', function (e) {
                let $input = $(this).prev('input.qty');
                let val = parseInt($input.val());
                $input.val(val + 1).change();
            });

            $('.quantity').on('click', '.minus',
                function (e) {
                    let $input = $(this).next('input.qty');
                    var val = parseInt($input.val());
                    if (val > 1) {
                        $input.val(val - 1).change();
                    }
                });

        $(".submit").on("click", function (element) {
            var urll = $(this).attr("data-url");
            var url = urll + "/?id="+ $(this).attr("data-id");
            var qty = $(this).parent().parent().find(".qty").val();
            var link = url + "&qty=" + qty;
          //  console.log(link)

            
            
         
           window.location = link
            })
        });
</script>

EShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EShop.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Electronic Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Admin" asp-action="Product">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Products" asp-action="Index">Anonymous</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EShop 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>